CREATE TABLE REGION(
REGION_ID		INTEGER			NOT NULL,
REGION_NAME		VARCHAR(25)		NOT NULL,
constraint		REGION_ID_PK	primary key(REGION_ID)
);

CREATE TABLE JOB(
JOB_ID			VARCHAR(10)			NOT NULL,
JOB_TITLE		VARCHAR(35)			NOT NULL,
MIN_SALARY		INTEGER				NOT NULL,
MAX_SALARY		INTEGER				NOT NULL,
constraint		JOB_PK				primary key(JOB_ID)
);

CREATE TABLE JOB_GRADE(
GRADE_LEVEL			VARCHAR(4)			NOT NULL,
LOWER_SAL			INTEGER				NOT NULL,
HIGHEST_SAL			INTEGER				NOT NULL,
constraint			GRADE_LEVEL_PK		primary key(GRADE_LEVEL)
);

create TABLE COUNTRY(
COUNTRY_ID			CHAR(3)			NOT NULL,
COUNTRY_NAME		varchar(40)		NOT NULL,
REGION_ID			INTEGER			NOT NULL,
CONSTRAINT		COUNTRY_REGION_PK		primary key(COUNTRY_ID, REGION_ID),
constraint COUNTRY_REGION_FK		foreign key(REGION_ID) references REGION(REGION_ID)
);

CREATE TABLE LOCATION(
LOCATION_ID				VARCHAR(25)				NOT NULL,
STREET_ADDRESS			VARCHAR(12)				NOT NULL,
POSTAL_CODE				VARCHAR(30)				NOT NULL,
CITY					VARCHAR(30)				NOT NULL,
STATE_PROVINCE			VARCHAR(12)				NOT NULL,
COUNTRY_ID				CHAR(3)					NOT NULL,
constraint				LOCATION_COUNTRY_PK		primary key(LOCATION_ID, COUNTRY_ID),
CONSTRAINT 				LOCATION_COUNTRY_FK		foreign key(COUNTRY_ID)	
references COUNTRY(COUNTRY_ID)
);

CREATE TABLE DEPARTMENT(
DEPARTMENT_ID		INTEGER			NOT NULL,
DEPARTMENT_NAME		VARCHAR(30)		NOT NULL,
MANAGER_ID			INTEGER			NOT NULL,
LOCATION_ID			VARCHAR(25)		NOT NULL,
constraint			DEPARTMENT_PK	primary key(DEPARTMENT_ID, LOCATION_ID),
CONSTRAINT			DEPARTMENT_FK	foreign key (LOCATION_ID)
									REFERENCES LOCATION (LOCATION_ID)
);

Create Table empLoyee(
EMPLOYEE_ID		integer			not null,
FIRST_NAME		varchar(20)		not null,
LAST_NAME		varchar(25)		not null,
EMAIL			varchar(35)		not null,
PHONE_NUMBER	varchar(30)		NOT NULL,
HIRE_DATE		DATE			NOT NULL,
JOB_ID			VARCHAR(20)		NOT NULL,
SALARY			INTEGER			NOT NULL,
COMMISSION_PCT	INTEGER			NOT NULL,
MANAGER_ID		INTEGER			NOT NULL,
DEPARTMENT_ID	INTEGER			not null,
CONSTRAINT	EMPLOYEE_PK		primary key(EMPLOYEE_ID, DEPARTMENT_ID, JOB_ID),
CONSTRAINT	EMPLOYEE_FK	foreign key(JOB_ID)
								REFERENCES JOB (JOB_ID),
CONSTRAINT	EMPLOYEE_FK1	foreign key(DEPARTMENT_ID)
								REFERENCES DEPARTMENT(DEPARTMENT_ID)
);

CREATE TABLE JOB_HISTORY( 
EMPLOYEE_ID		INTEGER				NOT NULL,
START_DATE		DATE				NOT NULL,
END_DATE		DATE				NOT NULL,
JOB_ID			VARCHAR(10)			NOT NULL,
DEPARTMENT_ID	INTEGER				NOT NULL,
constraint		EMPLOYEE_ID_PK		primary key(START_DATE, DEPARTMENT_ID, EMPLOYEE_ID, JOB_ID),
constraint 		JOB_HISTORY_FK 		foreign key(JOB_ID) references JOB(JOB_ID),
CONSTRAINT		JOB_DEPARTMENT_FK 	FOREIGN KEY(DEPARTMENT_ID) 
									REFERENCES DEPARTMENT(DEPARTMENT_ID),
constraint		JOB_HISTORY_DEPARTMENT_FK foreign key(EMPLOYEE_ID) 
										references EMPLOYEE(EMPLOYEE_ID)

);
